# ==============================
# Datasource
# ==============================
spring.datasource.url=jdbc:postgresql://localhost:55434/rental-service-db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# ==============================
# Server
# ==============================
server.port=8093

# ==============================
# Application name (opcional, útil para logs)
# ==============================
spring.application.name=rental-service

# ==============================
# URLs de servicios externos
# ==============================
services.car-service.url=${CAR_SERVICE_URL:http://localhost:8091}
services.user-service.url=${USER_SERVICE_URL:http://localhost:8092}