# ==============================
# Carga del .env compartido en /infra
# ==============================
spring.config.import=optional:file:../infra/.env[.properties]

# ==============================
# Datasource
# ==============================
spring.datasource.url=${RENTAL_DB_URL:jdbc:postgresql://localhost:55434/rental-service-db}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# ==============================
# Server
# ==============================
server.port=8093

# ==============================
# Application name (opcional, útil para logs)
# ==============================
spring.application.name=rental-service

# ==============================
# URLs de servicios externos
# ==============================
services.car-service.url=${CAR_SERVICE_URL:http://localhost:8091}
services.user-service.url=${USER_SERVICE_URL:http://localhost:8092}